version: '3.8'

networks:
  ed-network:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - ed-network

  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
   
    depends_on:
      - backend
    networks:
      - ed-network
